[ENG-7094][eas-build-job] improve job image validation
expo/eas-build pull request #182
Opened 2023-01-02 12:14 UTC by szdziedzic

# Why

https://linear.app/expo/issue/ENG-7094/better-error-handling-when-image-is-valid-but-doesnt-exist-on

We want to validate images by taking resource class into account. We want to move image sanitization logic to the `turtle-v2` repo so we don't have to publish `eas-build-job` every time that new image is added.

# How

Only validate if the `image` value is string type. Remove all other logic and transfer it to `turtle-v2`.

# Test Plan

Automated tests. Test with Turtle changes locally.

2023-01-03 09:35 UTC, wkozyra95 requested changes
I don't think we should have anything related to the resource class in this repo, validation should happen in turtle-api

2023-01-03 09:39 UTC, dsokal commented on packages/eas-build-job/src/job.ts
> +export const JobPlatfomSchema = Joi.object<Job>({
```suggestion
export const JobPlatformSchema = Joi.object<Job>({
```

2023-01-03 09:39 UTC, dsokal commented on packages/eas-build-job/src/job.ts
> +export const JobPlatfomSchema = Joi.object<Job>({
Also, can you verify this is not used elsewhere? E.g. in other repos.

2023-01-03 09:39 UTC, dsokal commented on packages/eas-build-job/src/job.ts
> +function validateJobPlatform(rawJob: object): Platform {
```suggestion
function sanitizeJobPlatform(rawJob: object): Platform {
```

2023-01-03 09:39 UTC, dsokal commented on packages/eas-build-job/src/job.ts
> +function validateJobPlatform(rawJob: object): Platform {
Usually: 
- `validate...` only validates the input, can throw an error, but does not return anything
- `sanitize...` validates the input, can throw an error, and returns the validated (and potentially changed) input

2023-01-20 12:54 UTC, dsokal approved these changes

2023-01-20 15:20 UTC, merged